context("get_kolada_data")

test_that("getMetadata() is working", {
  df = getMetadata("municipality")
  expect_true(is.data.frame(df))
  expect_equal(df[6, "values.id"], "2506")
  expect_equal(df[6, "values.title"], "Arjeplog")
  df = getMetadata("kpi")
  expect_true(is.data.frame(df))
  expect_equal(df[3, "values.id"], "N00005")
  expect_equal(df[3, "values.title"], "Utjämningssystemet enl resultaträkning, kr/inv")
  df = getMetadata("ou")
  expect_true(is.data.frame(df))
  expect_equal(df[5, "values.id"], "V15E011401301")
  expect_equal(df[5, "values.title"], "Sverigefinska sk, Uppl Väsby")
  df = getMetadata("kpi_groups")
  expect_true(is.data.frame(df))
  expect_equal(df[2, "member_id"], "U28129")
  expect_equal(df[2, "member_title"], "Andel personer med en aktuell genomförandeplan.")
  df = getMetadata("municipality_groups")
  expect_true(is.data.frame(df))
  expect_equal(df[1, "member_id"], "1263")
  expect_equal(df[1, "member_title"], "Svedala")
})
